# Generated by Django 3.1.1 on 2020-09-11 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_videos_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_open',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.IntegerField(blank=True, null=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fire.floor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fire.userinfo')),
            ],
        ),
    ]
