# Generated by Django 3.1.1 on 2020-09-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_auto_20200911_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, null=True)),
                ('application_time', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'course_application',
            },
        ),
        migrations.CreateModel(
            name='FriendApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_content', models.CharField(blank=True, max_length=200, null=True)),
                ('application_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('handle_content', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant', to='fire.userinfo')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='fire.userinfo')),
            ],
            options={
                'db_table': 'friend_application',
            },
        ),
        migrations.CreateModel(
            name='FriendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to='fire.userinfo')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to='fire.userinfo')),
            ],
            options={
                'db_table': 'friend_record',
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.IntegerField(blank=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='fire.userinfo')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='fire.userinfo')),
            ],
            options={
                'db_table': 'private_message',
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(blank=True, max_length=200, null=True)),
                ('message_content', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.IntegerField(blank=True, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fire.userinfo')),
            ],
            options={
                'db_table': 'system_message',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='watch_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userplayrecords',
            name='played_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video_viewed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='likerecord',
            table='like_record',
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fire.course'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fire.userinfo'),
        ),
    ]
