# Generated by Django 3.1.1 on 2020-09-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0004_auto_20200915_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fire.userinfo'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fire.userinfo'),
        ),
    ]
